# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        awsflysystem:
            adapter: 'asyncaws'
            options:
                client: 'aws_client_service'
                bucket: '%env(BUCKET)%'
                prefix: ''