services:
    php-cli:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: Dockerfile-dev
        volumes:
            - '${HOME}/.composer/:/root/.composer'
            - './files:/data/productsup'
            - './:/cde/app'
        stdin_open: true
        working_dir: /cde/app
