parameters:
    .container.dumper.inline_factories: true
    temp_filename: 'temp.parquet'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $accessKeyId: '%env(ACCESS_KEY_ID)%'
            $secretAccessKey: '%env(SECRET_ACCESS_KEY)%'
            $bucket: '%env(BUCKET)%'
            $region: '%env(REGION)%'
            $tempFilename: '%temp_filename%'
            $filename: '%env(FILE_NAME)%'

    Productsup\BinCdeAmazonS3Parquet\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    AsyncAws\SimpleS3\SimpleS3Client:
        factory: ['Productsup\BinCdeAmazonS3Parquet\Import\Infrastructure\Transporter\Factory\S3ClientFactory', 'make']

    League\Flysystem\FilesystemAdapter:
        factory: ['Productsup\BinCdeAmazonS3Parquet\Import\Infrastructure\Transporter\Factory\S3AdapterFactory', 'make']

    League\Flysystem\Filesystem:
        factory: ['Productsup\BinCdeAmazonS3Parquet\Import\Infrastructure\Transporter\Factory\FilesystemFactory', 'make']

    Productsup\BinCdeAmazonS3Parquet\Import\Application\Importer:
        $converter: '@Productsup\BinCdeAmazonS3Parquet\Import\Infrastructure\DuckDb\ParquetFileConverter'


when@dev:
    services:
        Productsup\DK\Connector\Application\Feed\OutputFeedForImport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileOutputFeedForImport'
        Productsup\DK\Connector\Application\Feed\OutputFeedForExport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileOutputFeedForExport'
        Productsup\DK\Connector\Application\Feed\InputFeedForExportDelta: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileInputFeedForExportDelta'
        Productsup\DK\Connector\Application\Feed\InputFeedForExport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileInputFeedForExport'
        Productsup\DK\Connector\Application\Logger\ConnectorLogger: '@Productsup\DK\Connector\Infrastructure\Logger\StandardLogger'
