parameters:
    .container.dumper.inline_factories: true
    temp_filename: 'temp.parquet'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $tempFilename: '%temp_filename%'
            $filename: '%env(FILE_NAME)%'

    Productsup\BinCdeAmazonS3Parquet\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Productsup\BinCdeAmazonS3Parquet\Import\Application\Importer:
        $converter: '@Productsup\BinCdeAmazonS3Parquet\Import\Infrastructure\Converter\ParquetFileConverter'

    aws_client_service:
        class: 'AsyncAws\S3\S3Client'

when@dev:
    services:
        Productsup\DK\Connector\Application\Feed\OutputFeedForImport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileOutputFeedForImport'
        Productsup\DK\Connector\Application\Feed\OutputFeedForExport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileOutputFeedForExport'
        Productsup\DK\Connector\Application\Feed\InputFeedForExportDelta: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileInputFeedForExportDelta'
        Productsup\DK\Connector\Application\Feed\InputFeedForExport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileInputFeedForExport'
        Productsup\DK\Connector\Application\Logger\ConnectorLogger: '@Productsup\DK\Connector\Infrastructure\Logger\StandardLogger'
